app:
  version: v1.0.0
  host: 0.0.0.0:7000
  ssl: off
  crossDomain: on
  tracing:
    agent: 127.0.0.1:6831
    type: const
    param: 1
    is_trace: false
  upfileDir: ./upfile
  upfileBase: .
cache:
  driver: redis
  params: redis://:@127.0.0.1:6379/0
redis: redis://:@127.0.0.1:6379/1
logger:
  prefix: web
  file: go-disc-srv
  dir: ./cachedir/log
  mask: 4
dbmastersqlite3:
  driver: sqlite3
  host: go.disc.srv.db
dbslaversqlite3:
  driver: sqlite3
  host: go.disc.srv.db
dbmaster:
  driver: mysql
  host: root:@tcp(127.0.0.1:3306)/go_disc_srv?charset=utf8mb4
  maxOpenConns: 128
  maxIdleConns: 64
dbslaver:
  driver: mysql
  host: root:@tcp(127.0.0.1:3306)/go_disc_srv?charset=utf8mb4
  maxOpenConns: 128
  maxIdleConns: 64